title: Burden of Proof
description: Text analysis and visualization of the DMCA Section 1201 exemption rulemaking corpus
baseurl: "/burdenofproof"
url: "https://blprnt.github.io"

markdown: kramdown
highlighter: rouge
permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: default
